# -*- coding: utf-8 -*-
"""First code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7cEdhdyd6Diz-HeI5C0gNwf03Tj_WJF
"""

print("helllo world")